### PR TITLE
add legacy fabric support

### PR DESCRIPTION
**Pull request by arthurbambou**
superseeds #5

### CODE REVIEW

**Comment by jamierocks** [comment]
This passes off third-party intermediaries as being Fabric's - they should have unique uid.

**Comment by arthurbambou** [comment]
Doesn't FabricLoader depend on "net.fabricmc.intermediary" component to run? Changing the uid of LegacyFabric intermediary will require to change this too in this case 🤔.

**Comment by arthurbambou** [comment]
I tried to keep them separated at least in the upstream-meta repo, but not sure how to do it for the multimc-meta one

**Comment by jamierocks** [comment]
I would not expect MultiMC to pass this off as Fabric anyway, it's a third-party project.

> Doesn't FabricLoader depend on "net.fabricmc.intermediary" component to run?

Yes it does.

> Changing the uid of LegacyFabric intermediary will require to change this too in this case

No it shouldn't. I can think of two solutions to this off the top of my head:
1. Have a Legacy Fabric 'Fabric Loader' component, which depends on it's own intermediaries.
2. Remove the requirement from the Fabric Loader component.

**Comment by arthurbambou** [comment]
Updated accordingly

**Comment by arthurbambou** [comment]
How do I add "noapplet" trait to legacy fabric variant of Loader?

**Comment by arthurbambou** [comment]
Ready for review

**Pull request closed without merging**
